version: "3.8"

services:
    ### PostgreSQL Database ###
  bo-db:
    image: postgres
    container_name: "banks-operations-db"
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_DB="bank_operations"
      - POSTGRES_USER="hallecraft"
      - POSTGRES_PASSWORD="manager123"
      - POSTGRES_ENABLE_SSL="NO"
    volumes:
      - data_bank_operations:/var/lib/postgresql/data  
    networks:
      - bo-networks
    ### Golang Web API ###
  bo-api:
    image: golang
    depends_on:
      - bo-db
    environment:
      - DB_USERNAME="hallecraft"
      - DB_PASSWORD="manager123"
      - DB_DB="bank_operations"
      - DB_HOST="bo-db"
      - DB_PORT="5432"
    ports:
      - 8000:8000
    networks:
      - bo-networks

volumes:
  data_bank_operations:

networks:
  bo-networks:
    driver: bridge
      